site_name: site_name
site_url: https://IceCubeQq.gitgub.io/MkDocsTest/

nav:
  - Home: index.md
  - About: about.md
  - Acquaintance: acquaintance.md

plugins:
  - search:
      lang: 'ru'

theme:
  name: material
  palette:

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light theme

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark theme

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name:
          Switch to auto (OS settings)

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences